=== TNick/FlowVR/contrib/portutils/flowvr-parse/dtd/metamoduledesc.dtd
<!ELEMENT metamoduledesc (metamoduledescription*)>
<!ELEMENT metamoduledescription (run+,modulelist*)>
<!ATTLIST metamoduledescription
          id CDATA #IMPLIED
>
<!ELEMENT run (#PCDATA|nb|host|hostlist|machinefile|template|metamoduleid)*>
<!ATTLIST run
          id CDATA #IMPLIED
          shell CDATA #IMPLIED
>
<!ELEMENT modulelist (script|module)*>
<!ATTLIST modulelist
          id CDATA #IMPLIED
>
<!ELEMENT script (#PCDATA|nb|host|hostlist|machinefile|template|metamoduleid)*>
<!ATTLIST script
          id CDATA #IMPLIED
          shell CDATA #IMPLIED
>

<!ELEMENT hostlist EMPTY>

<!ELEMENT nb EMPTY>
<!ELEMENT host      (#PCDATA)>
<!ATTLIST host
          id  CDATA #IMPLIED
>

<!ELEMENT machinefile EMPTY>
<!ELEMENT template (#PCDATA)>
<!ATTLIST template
          id CDATA #IMPLIED
>

<!ELEMENT metamoduleid EMPTY>


<!ELEMENT module (modulename,hostname,input?,output?,tracelist*)>

<!ELEMENT hostname (#PCDATA|host|template)*>
<!ELEMENT modulename (#PCDATA|host|template|metamoduleid|nb)*>


<!ELEMENT input (port*)>
<!ELEMENT output (port*)>
<!ELEMENT port (datatype?,stamplist?)>
<!ATTLIST port
          id CDATA #REQUIRED
>

<!ELEMENT datatype (#PCDATA)>

<!ELEMENT stamplist (stamp*)>
<!ELEMENT stamp (int|float|string|array|binary)>
<!ATTLIST stamp
          name CDATA #REQUIRED
	  size CDATA #REQUIRED
>
<!ELEMENT int EMPTY>
<!ELEMENT float EMPTY>
<!ELEMENT string EMPTY>
<!ELEMENT binary EMPTY>
<!ATTLIST binary
          size CDATA #REQUIRED
>
<!ELEMENT array (int|float|string|array|binary)>
<!ATTLIST array
          size CDATA #REQUIRED
>

<!ELEMENT tracelist (trace+)>

<!ELEMENT trace  (data)>
<!ATTLIST trace
          id CDATA #REQUIRED
>


<!ELEMENT data (int|float|string|array|binary)+>

=== TNick/FlowVR/contrib/vtk-flowvr/xml/vtk.desc.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE metamoduledesc  SYSTEM "http://flowvr.sf.net/flowvr-parse/dtd/metamoduledesc.dtd" >
<metamoduledesc>
 <metamoduledescription>
  <run>flowvr-run-ssh -e DISPLAY <template id="display">${DISPLAY:-:0}</template> <host>localhost</host> vtk <template id="script">../Examples/Tcl/warpComb.tcl</template></run>
  <modulelist>
   <module>
    <modulename><metamoduleid/></modulename>
    <hostname><host>localhost</host></hostname>
    <input>
      <port id="beginIt"><datatype/></port>
    </input>
    <output>
      <port id="scene"><datatype/></port>
      <port id="endIt"><datatype/></port>
    </output>
   </module>
  </modulelist>
 </metamoduledescription>
</metamoduledesc>

=== TNick/FlowVR/contrib/vtk-flowvr/xml/vtkflowvr.desc.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE metamoduledesc  SYSTEM "http://flowvr.sf.net/flowvr-parse/dtd/metamoduledesc.dtd" >
<metamoduledesc>
<metamoduledescription>
<run>flowvr-run-ssh -e DISPLAY ${DISPLAY:-:0} <host>localhost</host> vtk <template id="script">../Examples/Tcl/warpComb.tcl</template></run>
<modulelist>
  <script shell="/bin/bash">
    echo '  &lt;module id="<metamoduleid/>" host="<host/>"&gt;';
    echo '    &lt;input&gt;';
    for i in <template id="inputs">beginIt</template>;
    do
      echo "      &lt;port id=\"$i\"&gt;";
      echo '      &lt;datatype/&gt;';
      echo '      &lt;/port&gt;';
    done
    echo '    &lt;/input&gt;';
    echo '    &lt;output&gt;';
    for i in <template id="outputs">endIt</template>;
    do
      echo "      &lt;port id=\"$i\"&gt;";
      echo '      &lt;datatype/&gt;';
      echo '      &lt;/port&gt;';
    done
    echo '    &lt;/output&gt;';
    echo '  &lt;/module&gt;';
  </script>
</modulelist>
</metamoduledescription>
</metamoduledesc>

=== TNick/FlowVR/contrib/portutils/flowvr-parse/test/vision.desc.xml
<?xml version="1.0" encoding="LATIN1"?>
<!DOCTYPE metamoduledesc  SYSTEM "http://flowvr.sf.net/flowvr-parse/dtd/metamoduledesc.dtd" >

<metamoduledesc>
  <metamoduledescription id="vision1">
    <run id="1CPU" shell="bash">Use and "id" attribute to distinguish between different &lt;run&gt; </run>
    <run id="2CPU">template A=<template id="A"/> template out=<template id="out"/></run>
    <run>  Use XML predefined entities: &amp; &quot; &lt; &gt; &apos; or even  &#xA9; </run>

     <modulelist>
     <script>echo "script <metamoduleid/>: there are  priorities in template and host resolution. For instance template A=<template id="A"/> have a different value for the run command"</script>
     <script shell="tcsh">echo "script <metamoduleid/>: whitespace (including newlines) are  preserved during parsing"</script>
     <script shell="bash">echo "script <metamoduleid/>:"; ls -al <metamoduleid/>.desc.xml</script>
     <script shell="sh">echo "script <metamoduleid/>: the template out=<template id="out"/> affect all metamodules(unless shadowed by an inner definition)"</script>
     <script>echo "script <metamoduleid/>: here a template=<template id="vision2">DEFAULT VALUE</template>"</script>
     <script>echo "script <metamoduleid/>: here a host=<host id="vision2">DEFAULT VALUE</host> <host id="vision2">DEFAULT VALUE</host>"</script>
    </modulelist>

     <modulelist id="1">
     <script shell="bash">echo "script <metamoduleid/>: Like for &lt;run&gt;   use attributes to distinguish between module lists"</script>
    </modulelist> 
 </metamoduledescription>

  <metamoduledescription id="vision2">
    <run shell="bash">One file can contain several %lt;metamoduledescirptions%gt; but it should be avoided</run>
     <modulelist>
     <script shell="bash">echo "nothing"</script>
    </modulelist>
 </metamoduledescription>

</metamoduledesc>

=== TNick/FlowVR/contrib/vtk-flowvr/xml/vtkpara.desc.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE metamoduledesc  SYSTEM "http://flowvr.sf.net/flowvr-parse/dtd/metamoduledesc.dtd" >
<metamoduledesc>
<metamoduledescription>
<run>flowvr-run-ssh -p -e DISPLAY <template id="display">${DISPLAY:-:0}</template> '<hostlist />' vtk <template id="script"/> <template id="args"/></run>
<modulelist>
  <script shell="/bin/bash">
count=0;
for h in <hostlist/>;
do
    echo "  &lt;module id=\"<metamoduleid/>/$count\" host=\"$h\"&gt;";
    echo '    &lt;input&gt;';
    for i in <template id="inputs">beginIt</template>;
    do
      echo "      &lt;port id=\"$i\"&gt;";
      echo '      &lt;datatype/&gt;';
      echo '      &lt;/port&gt;';
    done
    echo '    &lt;/input&gt;';
    echo '    &lt;output&gt;';
    for i in <template id="outputs">endIt</template>;
    do
      echo "      &lt;port id=\"$i\"&gt;";
      echo '      &lt;datatype/&gt;';
      echo '      &lt;/port&gt;';
    done
    echo '    &lt;/output&gt;';
    echo '  &lt;/module&gt;';
let count+=1;
done
  </script>
</modulelist>
</metamoduledescription>
</metamoduledesc>

=== TNick/FlowVR/contrib/portutils/flowvr-parse/test/viz.desc.xml
<?xml version="1.0" encoding="LATIN1"?>
<!DOCTYPE metamoduledesc  SYSTEM "http://flowvr.sf.net/flowvr-parse/dtd/metamoduledesc.dtd" >

<metamoduledesc>
  <metamoduledescription>
    <run shell="bash">run  <metamoduleid/>: Launching script for <metamoduleid/>. Can use templates :  hostname=<host id="projct1"/>  Projector type=<template id="projcttype"/> metamodule id=<metamoduleid/>   hostlist=<hostlist/>  machinefile=<machinefile/> nb=<nb/></run>

   <modulelist>
     <module>
     <modulename><metamoduleid/></modulename>
     <hostname><host id="projct1"/></hostname>
     <output>
      <port id="pos">
        <datatype>data</datatype>
	<stamplist>
          <stamp name="source" size="8">
	      <string/>
	  </stamp>
          <stamp name="it" size="4">
	      <int/>
	  </stamp>
	</stamplist>
      </port>
    </output>
    </module>

     <script shell="bash">echo "script<metamoduleid/>: Do nothing, just show that templates are resolved: hostname=<host id="projct1"/>  Projector type=<template id="projcttype"/> metamodule id=<metamoduleid/>  template out=<template id="out"/>"</script>

  </modulelist>
 </metamoduledescription>
</metamoduledesc>
