=== TNick/FlowVR/contrib/portutils/flowvr-parse/dtd/metamodulelist.dtd
<!ELEMENT metamodulelist ((template|host)*,metamodule+)>

<!ELEMENT metamodule (metamoduledescription,(template|host)*,run,modulelist)>
<!ATTLIST metamodule
          id CDATA #REQUIRED>

<!ELEMENT metamoduledescription (#PCDATA)>
<!ATTLIST metamoduledescription
          id CDATA #IMPLIED>

<!ELEMENT run (host|template)*>
<!ATTLIST run
          id CDATA #IMPLIED
          shell CDATA #IMPLIED>

<!ELEMENT modulelist (host|template)*>
<!ATTLIST modulelist
          id CDATA #IMPLIED>

<!ELEMENT host (#PCDATA)>
<!ATTLIST host 
          id CDATA #IMPLIED>

<!ELEMENT template (#PCDATA)>
<!ATTLIST template 
          id CDATA #IMPLIED>

=== TNick/FlowVR/contrib/vtk-flowvr/Examples/Tcl/warpComb/net/warpComb.mml.xml
<?xml version="1.0" encoding="LATIN1" ?>
<!DOCTYPE metamodulelist  SYSTEM "http://flowvr.sf.net/flowvr-parse/dtd/metamodulelist.dtd">
<metamodulelist>
    <metamodule id="Visu">
      <metamoduledescription>flowvr-renderer.desc.xml</metamoduledescription>
	<template id="args">--white</template>
        <host>localhost</host>
        <run />
        <modulelist />
    </metamodule>
    <metamodule id="Vtk">
      <metamoduledescription>vtk.desc.xml</metamoduledescription>
	<template id="script">$FLOWVR_PWD/modules/warpComb.tcl</template>
        <host>localhost</host>
        <run />
        <modulelist />
    </metamodule>
</metamodulelist>

=== TNick/FlowVR/contrib/vtk-flowvr/Examples/Tcl/fluid2d/net/fluid2d.mml.xml
<?xml version="1.0" encoding="LATIN1" ?>
<!DOCTYPE metamodulelist  SYSTEM "http://flowvr.sf.net/flowvr-parse/dtd/metamodulelist.dtd">
<metamodulelist>
    <metamodule id="Visu">
      <metamoduledescription>vtkflowvr.desc.xml</metamoduledescription>
        <host>localhost</host>
	<template id="script">$FLOWVR_PWD/modules/fluid2d.tcl</template>
	<template id="inputs">beginIt density</template>
        <run />
        <modulelist />
    </metamodule>
    <metamodule id="Simu">
      <metamoduledescription id="fluid-mpi">fluid-mpi.desc.xml</metamoduledescription>
      <host>localhost</host>
      <run id="local"/>
      <modulelist id="local"/>
    </metamodule>
</metamodulelist>

=== TNick/FlowVR/contrib/vtk-flowvr/Examples/Tcl/xmas/net/xmas.mml.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE metamodulelist  SYSTEM "http://flowvr.sf.net/flowvr-parse/dtd/metamodulelist.dtd" >
<metamodulelist>
  <metamodule id="Visu">
    <metamoduledescription>flowvr-renderer.desc.xml</metamoduledescription>
    <template id="args">--black --zoom 40 --rotate --dt 0.18</template>
    <host>localhost</host>
    <run />
    <modulelist />
  </metamodule>
  <metamodule id="VTK">
    <metamoduledescription>vtk.desc.xml</metamoduledescription>
    <template id="script">$FLOWVR_PWD/modules/xmas.tcl</template>
    <host>localhost</host>
    <run/>
    <modulelist/>
  </metamodule>
</metamodulelist>

=== TNick/FlowVR/contrib/vtk-flowvr/Examples/Tcl/fluid3d1render/net/fluid3dpara.mml.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE metamodulelist  SYSTEM "http://flowvr.sf.net/flowvr-parse/dtd/metamodulelist.dtd" >
<metamodulelist>
  <metamodule id="Visu">
    <metamoduledescription>flowvr-renderer.desc.xml</metamoduledescription>
    <template id="args">--rotateX -90 --rotateY 60 @400x300@1x2@</template>
    <host>localhost</host>
    <host>localhost</host>
    <run />
    <modulelist />
  </metamodule>
  <template id="file">$VTK_FLOWVR_DATA_ROOT/fluid3d1.fvr</template>
  <metamodule id="FluidDistRead">
    <metamoduledescription>flowvr/fread.desc.xml</metamoduledescription>
    <host>localhost</host>
    <run/>
    <modulelist/>
  </metamodule>
  <metamodule id="VTK">
    <metamoduledescription>vtkpara.desc.xml</metamoduledescription>
    <template id="script">$FLOWVR_PWD/modules/fluid3d1render.tcl</template>
    <template id="args">2 1</template>
    <template id="inputs">beginIt in</template>
    <template id="outputs">endIt scene</template>
    <host>localhost</host>
    <host>localhost</host>
    <run/>
    <modulelist/>
  </metamodule>
</metamodulelist>

=== TNick/FlowVR/contrib/portutils/flowvr-parse/test/vizvis.mml.xml
<?xml version="1.0" encoding="LATIN1"?>
<!DOCTYPE metamodulelist  SYSTEM "http://flowvr.sf.net/flowvr-parse/dtd/metamodulelist.dtd" >

<metamodulelist>
  <template id="out">GLOBAL TEMPLATE</template>
      <host>node10</host> 
  <metamodule id="vision">
      <metamoduledescription id="vision1">vision.desc.xml</metamoduledescription>
      <host>node1</host> 
      <host id="camera2">node2</host> 
      <host>node3</host> 
      <run><template id="A">RUN</template></run>
      <modulelist><template id="A">MODULELIST</template></modulelist>
  </metamodule>

  <metamodule id="vizu">
      <metamoduledescription>viz.desc.xml</metamoduledescription>
      <template id="projcttype">LCD</template>
      <host>node2</host> 
      <host id="projct1">node1</host> 
      <host>node3</host> 
      <run/>
      <modulelist/>
  </metamodule>
</metamodulelist>
